import React, { useState } from 'react'
import { ItemImage } from '../../atoms/ItemImage'
import { EquipmentItemSquares } from '../../molecules/Equipment/EquipmentItemSquares'

export function EquipmentView({ equipment, selectedItem, setSelectedItem }) {
  return (
    <div className="container flex w-min h-min m-0.5 border rounded-xl px-4 bg-gray-800">
      <div>
        <EquipmentItemSquares
          item={equipment.mainhand}
          size={12}
          selectedItem={selectedItem}
          setSelectedItem={setSelectedItem}
        />
        <EquipmentItemSquares
          item={equipment.offhand}
          size={12}
          selectedItem={selectedItem}
          setSelectedItem={setSelectedItem}
        />
        <EquipmentItemSquares
          item={equipment.ammo}
          size={12}
          selectedItem={selectedItem}
          setSelectedItem={setSelectedItem}
        />
        <EquipmentItemSquares
          item={equipment.cloak}
          size={12}
          selectedItem={selectedItem}
          setSelectedItem={setSelectedItem}
        />
        <EquipmentItemSquares
          item={equipment.mask}
          size={12}
          selectedItem={selectedItem}
          setSelectedItem={setSelectedItem}
        />
      </div>
      <div className="flex flex-col justify-between items-center">
        <div className="flex mx-4">
          <EquipmentItemSquares
            item={equipment.l_ring}
            size={8}
            selectedItem={selectedItem}
            setSelectedItem={setSelectedItem}
          />
          <EquipmentItemSquares
            item={equipment.l_earring}
            size={8}
            selectedItem={selectedItem}
            setSelectedItem={setSelectedItem}
          />
          <EquipmentItemSquares
            item={equipment.necklace}
            size={8}
            selectedItem={selectedItem}
            setSelectedItem={setSelectedItem}
          />
          <EquipmentItemSquares
            item={equipment.r_earring}
            size={8}
            selectedItem={selectedItem}
            setSelectedItem={setSelectedItem}
          />
          <EquipmentItemSquares
            item={equipment.r_ring}
            size={8}
            selectedItem={selectedItem}
            setSelectedItem={setSelectedItem}
          />
        </div>
        <div className="flex mx-4">
          <EquipmentItemSquares
            item={equipment.f_hat}
            size={8}
            selectedItem={selectedItem}
            setSelectedItem={setSelectedItem}
          />
          <EquipmentItemSquares
            item={equipment.f_suit}
            size={8}
            selectedItem={selectedItem}
            setSelectedItem={setSelectedItem}
          />
          <EquipmentItemSquares
            item={equipment.f_gloves}
            size={8}
            selectedItem={selectedItem}
            setSelectedItem={setSelectedItem}
          />
          <EquipmentItemSquares
            item={equipment.f_boots}
            size={8}
            selectedItem={selectedItem}
            setSelectedItem={setSelectedItem}
          />
        </div>
      </div>
      <div>
        <EquipmentItemSquares
          item={equipment.helmet}
          size={12}
          selectedItem={selectedItem}
          setSelectedItem={setSelectedItem}
        />
        <EquipmentItemSquares
          item={equipment.suit}
          size={12}
          selectedItem={selectedItem}
          setSelectedItem={setSelectedItem}
        />
        <EquipmentItemSquares
          item={equipment.gloves}
          size={12}
          selectedItem={selectedItem}
          setSelectedItem={setSelectedItem}
        />
        <EquipmentItemSquares
          item={equipment.boots}
          size={12}
          selectedItem={selectedItem}
          setSelectedItem={setSelectedItem}
        />
        <EquipmentItemSquares
          item={equipment.mount}
          size={12}
          selectedItem={selectedItem}
          setSelectedItem={setSelectedItem}
        />
      </div>
    </div>
  )
}
